language: node_js
node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6
jobs:  
  include:
    - stage: build
      name: "Build"
      script: npm run build
    # - stage: test
    #   name: "Tests"
    #   script: npm run test